package gov.lanl.micot.util.math.solver.ipopt;

/**
 * Enum of the different solver status in IpOpt
 * @author Russell Bent
 *
 */
public enum IpOptStatus {  
      IPOPT_STATUS_SOLVE_SUCCEEDED,
      IPOPT_STATUS_SOLVED_TO_ACCEPTABLE_LEVEL,
      IPOPT_STATUS_INFEASIBLE_PROBLEM_DETECTED,
      IPOPT_STATUS_SEARCH_DIRECTION_BECOMES_TOO_SMALL,
      IPOPT_STATUS_DIVERGING_ITERATES,
      IPOPT_STATUS_USER_REQUESTED_STOP,
      IPOPT_STATUS_FEASIBLE_POINT_FOUND,
      IPOPT_STATUS_MAXIMUM_ITERATIONS_EXCEEDED,
      IPOPT_STATUS_RESTORATION_FAILED,
      IPOPT_STATUS_ERROR_IN_STEP_COMPUTATION,
      IPOPT_STATUS_MAXIMUM_CPUTIME_EXCEEDED,
      IPOPT_STATUS_NOT_ENOUGH_DEGREES_OF_FREEDOM,
      IPOPT_STATUS_INVALID_PROBLEM_DEFINITION,
      IPOPT_STATUS_INVALID_OPTION,
      IPOPT_STATUS_INVALID_NUMBER_DETECTED,
      IPOPT_STATUS_UNRECOVERABLE_EXCEPTION,
      IPOPT_STATUS_NONIOPT_EXCEPTION_THROWN,
      IPOPT_STATUS_INSUFFICIENT_MEMORY,
      IPOPT_STATUS_INTERNAL_ERROR
  }
