package gov.lanl.micot.infrastructure.ep.model.pfw;

/**
 * The constants associated with PFW Models
 * @author Russell Bent
 *
 */
public class PFWModelConstants {

  /**
   * Constructor
   */
  private PFWModelConstants() {    
  }

  //public static final String PFW_SWITCHED_SHUNT_AREA_KEY = "PFW_SWITCHED_SHUNT_AREA_KEY";
  //public static final String PFW_SWITCHED_SHUNT_ZONE_KEY = "PFW_SWITCHED_SHUNT_ZONE_KEY";
  public static final String PFW_SWITCHED_SHUNT_CONTROL_MODE_KEY = "PFW_SWITCHED_SHUNT_CONTROL_MODE_KEY";
  public static final String PFW_SWITCHED_SHUNT_NORMAL_STATUS_KEY = "PFW_SWITCHED_SHUNT_NORMAL_STATUS_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS1_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS1_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS2_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS2_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS3_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS3_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS4_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS4_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS5_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS5_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS6_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS6_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS7_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS7_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS8_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS8_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS9_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS9_KEY";
  public static final String PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS10_KEY = "PFW_SWITCHED_SHUNT_NUM_SUBSECTIONS10_KEY";  
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION1_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION1_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION2_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION2_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION3_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION3_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION4_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION4_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION5_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION5_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION6_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION6_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION7_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION7_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION8_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION8_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION9_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION9_SIZE_KEY";
  public static final String PFW_SWITCHED_SHUNT_SUBSECTION10_SIZE_KEY = "PFW_SWITCHED_SHUNT_SUBSECTION10_SIZE_KEY";

  public static final String PFW_LINE_BRANCH_RATING_DESGINATOR_KEY = "PFW_LINE_BRANCH_RATING_DESGINATOR_KEY";
  public static final String PFW_LINE_UNKNOWN_KEY                  = "PFW_LINE_UNKNOWN_KEY";

  public static final String PFW_TRANSFORMER_BRANCH_RATING_DESGINATOR_KEY = "PFW_TRANSFORMER_BRANCH_RATING_DESGINATOR_KEY";

  public static final String PFW_LEGACY_ID_KEY                            = "PFW_LEGACY_ID";
  //public static final String PFW_LEGACY_FROM_ID_KEY                       = "PFW_LEGACY_FROM_ID";
  //public static final String PFW_LEGACY_TO_ID_KEY                         = "PFW_LEGACY_TO_ID";

  
}
